# Generated by Django 4.0.2 on 2022-03-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='image/'),
            preserve_default=False,
        ),
    ]
